### ISSUE TITLE
TypeError in case pseudo files are not used

### ISSUE THREAD

**Issue by languitar** [projectaur/docker-stats-exporter#7]
```
>>> src.application.get_metrics()
No handlers could be found for logger "flask_caching"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/flask_caching/__init__.py", line 363, in decorated_function
    return f(*args, **kwargs)
  File "src/application.py", line 74, in get_metrics
    metrics = METRICS.next()
  File "src/application.py", line 90, in update_metrics
    parsed_metrics = parse_stats(metrics)
  File "src/application.py", line 108, in parse_api_metrics
    cpu_stats['cpu_usage'][stat_name]))
  File "src/application.py", line 142, in make_line
    int(metric)))
TypeError: int() argument must be a string or a number, not 'list'
```

**Comment by projectaur** [comment]
Fixed in version 0.7. See https://github.com/projectaur/docker-stats-exporter/commit/bda5c20c9a996146104d980a3bc327fd9dff66ae
